language: go
go:
  - '1.11'
sudo: false

script:
  - echo $PATH
  - curl -L -o $HOME/bin/reviewdog https://github.com/haya14busa/reviewdog/releases/download/0.9.11/reviewdog_linux_amd64
  - chmod a+x $HOME/bin/reviewdog
  - reviewdog -v
